USE [ChallengeFiapCyrela]
GO

CREATE TABLE [dbo].[Stage1_Marca](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Marca] [nvarchar](255) NULL,
	[Empreendimento] [nvarchar](255) NULL, 
	CONSTRAINT [PK_Stage1_Marca] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


