USE [ChallengeFiapCyrela]
GO

CREATE TABLE [dbo].[Stage1_Regiao](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Regiao] [nvarchar](255) NULL,
 CONSTRAINT [PK_Stage1_Regiao] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


