USE [ChallengeFiapCyrela]
GO

CREATE TABLE [dbo].[Stage2_Site](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Pagina] [varchar](50) NOT NULL,
	[Atividade] [varchar](255) NOT NULL,
	[DataEvento] [datetime2](7) NOT NULL,
 CONSTRAINT [Id_Stage2_Site] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


